# Configuration for the-welcome-bot - https://github.com/bash-bot/the-welcome-bot

# Message for a new user who open an issue
issueOpen: >
  Welcome to the project ttth!
  Thanks and congrats for opening your very first issue in this project.
  Hope you have a great time here :)

# Message for a new user who comments on an issue
issueComment: >
  Welcome to the project ttth!
  Thanks and congrats for your very first comment on this project.
  Checkout the Readme for more details on it.
  Want to contribute? Make an issue or submit a PR.
  Hope you have a great time here :)

# Message for a new user who opens a PR
prOpen: >
  Welcome to the project ttth!
  Thank you and congarts for your first PR on this project.
  We will review it soon!
  Hope you have a great time here :)

# Default message for a new user
welcomeMessage: >
  Welcome to the project ttth! Feel free to explore it.
  Checkout the Readme.md for more details on it.
  Want to contribute? Make an issue or submit a PR.
  You can check the contributing guides.
  Hope you have a great time here :)
