---
exclude_paths:
  - 'app/js/bootstrap/**/*'
  - 'app/js/fontawesome-free-web/**/*'
  - 'app/js/jquery/**/*'
  - 'app/js/jquery.modalLoading/*'
  - 'app/js/noty/**/*'
  - 'app/js/semver/**/*'
  - 'docs/**/*'
  - 'docs/jsdocs/**/*'
  - '.github/**'
  - '.github/**/*'
  - 'LICENSE'
  - 'README.md'
